name: PR • Build

on:
  pull_request:
    branches: ["**"]

permissions:
  contents: read

jobs:
  build:
    name: Build Next.js
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Build
        env:
          NEXT_TELEMETRY_DISABLED: 1
        run: |
          set -o pipefail
          npm run build 2>&1 | tee build.log

      - name: Upload build log (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-log
          path: build.log
